gintonicmatrix/gintonicmatrix/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='matrix:index')),
    path('matrix/', include('matrix.urls')),
    path('admin/', admin.site.urls),
]

gintonicmatrix/matrix/urls.py
from django.urls import path

from . import views

app_name = "matrix"
urlpatterns = [
    path("", views.index, name="index"),
    path(
        "<int:gin_id>/<int:tonic_id>/",
        views.evaluations,
        name="evaluations"),
    path(
        "<int:gin_id>/<int:tonic_id>/evaluate",
        views.evaluate,
        name="evaluate"),
    path("ranking", views.ranking, name="ranking")
]

gintonicmatrix/matrix/models.py
from django.db import models


class Drinker(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Gin(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tonic(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class GinTonicEvaluation(models.Model):
    class Rating(models.IntegerChoices):
        VeryGood = 4
        Good = 3
        Average = 2
        Bad = 1

    drinker = models.ForeignKey(Drinker, on_delete=models.PROTECT)
    gin = models.ForeignKey(Gin, on_delete=models.PROTECT)
    tonic = models.ForeignKey(Tonic, on_delete=models.PROTECT)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT)
    rating = models.IntegerField(choices=Rating.choices)
    created = models.DateTimeField("Rated on")

    def __str__(self):
        return f"{self.gin}-{self.tonic}+{self.ingredient} ({self.drinker})"

gintonicmatrix/matrix/views.py
import dataclasses
import itertools
import operator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone

from .models import Drinker, Gin, GinTonicEvaluation, Ingredient, Tonic


def index(request):
    gins = Gin.objects.order_by("name")
    tonics = Tonic.objects.order_by("name")
    drinkers = Drinker.objects.order_by("name")
    ingredients = Ingredient.objects.order_by("name")
    try:
        selected_drinker = Drinker.objects.get(pk=request.POST["drinker"])
    except (KeyError, ValueError, Drinker.DoesNotExist):
        selected_drinker = None
    try:
        selected_ingredient = Ingredient.objects.get(
            pk=request.POST["ingredient"])
    except (KeyError, ValueError, Ingredient.DoesNotExist):
        selected_ingredient = None
    evaluation_rows = []
    for tonic in tonics:
        evaluation_row = []
        for gin in gins:
            lookup = {"gin": gin, "tonic": tonic}
            if selected_drinker is not None:
                lookup["drinker"] = selected_drinker
            if selected_ingredient is not None:
                lookup["ingredient"] = selected_ingredient
            gin_tonic = GinTonicEvaluation.objects.filter(**lookup)
            if len(gin_tonic) == 0:
                evaluation_row.append((gin, None))
            else:
                mean = 0.0
                for evaluation in gin_tonic:
                    mean += evaluation.rating / len(gin_tonic)
                evaluation_row.append((gin, mean))
        tonic_rating = 0
        count = 0
        for row in evaluation_row:
            mean = row[1]
            if mean is not None:
                tonic_rating += mean
                count += 1
        if count > 0:
            tonic_rating /= count
        evaluation_rows.append((tonic_rating, tonic, evaluation_row))
    gin_ratings = []
    for i in range(len(gins)):
        gin_mean = 0
        count = 0
        for row in evaluation_rows:
            gin_tonic_mean = row[2][i][1]
            if gin_tonic_mean is not None:
                gin_mean += gin_tonic_mean
                count += 1
        if count > 0:
            gin_mean /= count
        gin_ratings.append(gin_mean)
    return render(
        request,
        "matrix/matrix.html",
        {"selected_drinker": selected_drinker,
         "selected_ingredient": selected_ingredient,
         "drinkers": drinkers,
         "gins": gins,
         "tonics": tonics,
         "ingredients": ingredients,
         "evaluation_rows": evaluation_rows,
         "gin_ratings": gin_ratings})


def evaluations(request, gin_id, tonic_id):
    gin = get_object_or_404(Gin, pk=gin_id)
    tonic = get_object_or_404(Tonic, pk=tonic_id)
    drinkers = Drinker.objects.all()
    ingredients = Ingredient.objects.all()
    gin_tonic = GinTonicEvaluation.objects.filter(
        gin=gin, tonic=tonic).order_by("-created")
    return render(request, "matrix/evaluations.html", {
        "gin": gin,
        "tonic": tonic,
        "evaluations": gin_tonic,
        "drinkers": drinkers,
        "ingredients": ingredients})


def evaluate(request, gin_id, tonic_id):
    gin = get_object_or_404(Gin, pk=gin_id)
    tonic = get_object_or_404(Tonic, pk=tonic_id)
    try:
        drinker = Drinker.objects.get(pk=request.POST["drinker"])
        ingredient = Ingredient.objects.get(pk=request.POST["ingredient"])
        rating = request.POST["rating"]
    except (ValueError,
            KeyError,
            Drinker.DoesNotExist,
            Ingredient.DoesNotExist):
        drinkers = Drinker.objects.all()
        ingredients = Ingredient.objects.all()
        gin_tonic = GinTonicEvaluation.objects.filter(gin=gin, tonic=tonic)
        return render(request, "matrix/evaluations.html", {
            "gin": gin,
            "tonic": tonic,
            "evaluations": gin_tonic,
            "drinkers": drinkers,
            "ingredients": ingredients,
            "error_message": "Bitte alle Felder ausfüllen"})
    GinTonicEvaluation(
        drinker=drinker,
        gin=gin,
        tonic=tonic,
        ingredient=ingredient,
        rating=rating,
        created=timezone.now()).save()
    return HttpResponseRedirect(
        reverse("matrix:evaluations", args=(gin_id, tonic_id)))


@dataclasses.dataclass
class GinTonicEvaluationCombination:
    name: str
    rating: float
    rating_count: int
    unique_rating_count: int


def _group_func(evaluation):
    return f"{evaluation.gin}-{evaluation.tonic} + {evaluation.ingredient}"


def _generate_combinations(evaluations) -> list[GinTonicEvaluationCombination]:
    combinations = []
    for key, evaluation in itertools.groupby(evaluations, _group_func):
        evaluation = list(evaluation)
        combinations.append(GinTonicEvaluationCombination(
            key,
            sum(i.rating for i in evaluation) / len(evaluation),
            len(evaluation),
            len({i.drinker for i in evaluation})))
    return combinations


def ranking(request):
    min_rating_count = int(request.POST.get("min_rating_count", 4))
    evaluations = GinTonicEvaluation.objects.order_by(
        "gin", "tonic", "ingredient")
    combinations = _generate_combinations(evaluations)
    combinations = [i for i in combinations if i.rating_count >= min_rating_count]
    combinations.sort(key=operator.attrgetter("rating"), reverse=True)
    return render(request, "matrix/ranking.html", {
        "combinations": combinations, "min_rating_count": min_rating_count})

gintonicmatrix/matrix/templates/matrix/evaluations.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'matrix/style.css' %}">

<!doctype html>

<p><a href="{% url 'matrix:index' %}">&ltZurück</a></p>

<h1>{{ gin }} - {{ tonic }}</h1>

<h2>Hinzufügen</h2>

<form action="{% url 'matrix:evaluate' gin.id tonic.id %}" method="post">
    {% csrf_token %}
    <select name="drinker">
        <option></option>
        {% for drinker in drinkers %}
        <option value="{{ drinker.id }}">{{ drinker }}</option>
        {% endfor %}
    </select>
    <select name="ingredient">
        <option></option>
        {% for ingredient in ingredients %}
        {% if selected_ingredient == ingredient %}
        <option value="{{ ingredient.id }}" selected>
            {% else %}
        <option value="{{ ingredient.id }}">{% endif %}
            {{ ingredient }}
        </option>
        {% endfor %}
    </select>
    <select name="rating">
        <option></option>
        <option value="4">4: Geil/Sehr gut</option>
        <option value="3">3: Gern/In Ordnung</option>
        <option value="2">2: Mittelmäßig/Wenn's sein muss</option>
        <option value="1">1: Nee</option>
    </select>
    <input type="submit" value="Speichern">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</form>

<h2>Übersicht</h2>

<table>
    <tr>
        <th>Datum</th>
        <th>Trinker</th>
        <th>Ingredient</th>
        <th>Bewertung</th>
    </tr>
    {% for evaluation in evaluations %}
    <tr>
        <td>{{ evaluation.created }}</td>
        <td>{{ evaluation.drinker }}</td>
        <td>{{ evaluation.ingredient }}</td>
        <td>{{ evaluation.rating }}</td>
    </tr>
    {% endfor %}
</table>

gintonicmatrix/matrix/templates/matrix/list.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'matrix/style.css' %}">

<!doctype html>
<table>
    <tr>
        <th></th>
        {% for item in gins %}
        <th>{{ item }}</th>
        {% endfor %}
    </tr>
    {% for tonic, evaluation in evaluation_rows %}
    <tr>
        <th>{{ tonic }}</th>
        {% for item in evaluation %}
            {% if item is None %}
            <td>-</td>
            {% else %}
            <td class="
                {% if item >= 3.75 %}_40{% endif %}
                {% if item < 3.75 and item >= 3.25 %}_35{% endif %}
                {% if item < 3.25 and item >= 2.75 %}_30{% endif %}
                {% if item < 2.75 and item >= 2.25 %}_25{% endif %}
                {% if item < 2.25 and item >= 1.75 %}_20{% endif %}
                {% if item < 1.75 and item >= 1.25 %}_15{% endif %}
                {% if item < 1.25 and item >= 0.75 %}_10{% endif %}
                {% if item < 0.75 and item >= 0.25 %}_05{% endif %}
                {% if item < 0.25 %}_00{% endif %}">
            {{ item }}
            </td>
            {% endif %}
        {% endfor %}
    </tr>
    {% endfor %}
</table>

gintonicmatrix/matrix/templates/matrix/matrix.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'matrix/style.css' %}">

<!doctype html>

<h1>Die Gin-Tonic-Matrix</h1>

<p><a href="{% url 'matrix:ranking' %}">&lt Zur Rangliste</a></p>

<form action="{% url 'matrix:index' %}" method="post">
    {% csrf_token %}
    <select name="drinker" onchange="this.form.submit()">
        <option value=none>Alle Trinker</option>
        {% for drinker in drinkers %}
        {% if selected_drinker == drinker %}
        <option value="{{ drinker.id }}" selected>
            {% else %}
        <option value="{{ drinker.id }}">{% endif %}
            {{ drinker }}
        </option>
        {% endfor %}
    </select>
    <select name="ingredient" onchange="this.form.submit()">
        <option value=none>Alle Ingredients</option>
        {% for ingredient in ingredients %}
        {% if selected_ingredient == ingredient %}
        <option value="{{ ingredient.id }}" selected>
            {% else %}
        <option value="{{ ingredient.id }}">{% endif %}
            {{ ingredient }}
        </option>
        {% endfor %}
    </select>
</form>

<table cellspacing="0" cellpadding="0">
    <tr>
        <td></td>
        <td></td>
        {% for gin_rating in gin_ratings %}
        {% if gin_rating == 0 %}
        <td>-</td>
        {% else %}
        <td class="
        {% if gin_rating >= 3.75 %}_40{% endif %}
        {% if gin_rating < 3.75 and gin_rating >= 3.25 %}_35{% endif %}
        {% if gin_rating < 3.25 and gin_rating >= 2.75 %}_30{% endif %}
        {% if gin_rating < 2.75 and gin_rating >= 2.25 %}_25{% endif %}
        {% if gin_rating < 2.25 and gin_rating >= 1.75 %}_20{% endif %}
        {% if gin_rating < 1.75 and gin_rating >= 1.25 %}_15{% endif %}
        {% if gin_rating < 1.25 %}_10{% endif %}">
            {{ gin_rating|floatformat:1 }}
        </td>
        {% endif %}
        {% endfor %}
    </tr>
    <tr>
        <td></td>
        <th></th>
        {% for item in gins %}
        <th style="width: 100px;">{{ item }}</th>
        {% endfor %}
    </tr>
    {% for tonic_rating, tonic, evaluation in evaluation_rows %}
    <tr>
        {% if tonic_rating == 0 %}
        <td>-</td>
        {% else %}
        <td class="
        {% if tonic_rating >= 3.75 %}_40{% endif %}
        {% if tonic_rating < 3.75 and tonic_rating >= 3.25 %}_35{% endif %}
        {% if tonic_rating < 3.25 and tonic_rating >= 2.75 %}_30{% endif %}
        {% if tonic_rating < 2.75 and tonic_rating >= 2.25 %}_25{% endif %}
        {% if tonic_rating < 2.25 and tonic_rating >= 1.75 %}_20{% endif %}
        {% if tonic_rating < 1.75 and tonic_rating >= 1.25 %}_15{% endif %}
        {% if tonic_rating < 1.25 %}_10{% endif %}">
            {{ tonic_rating|floatformat:1 }}
        </td>
        {% endif %}
        <th>{{ tonic }}</th>
        {% for gin, item in evaluation %}
        {% if item is None %}
        <td><a href="{% url 'matrix:evaluations' gin.id tonic.id %}" style="text-decoration: none;">
            <div>-</div>
        </a></td>
        {% else %}
        <td class="
                {% if item >= 3.75 %}_40{% endif %}
                {% if item < 3.75 and item >= 3.25 %}_35{% endif %}
                {% if item < 3.25 and item >= 2.75 %}_30{% endif %}
                {% if item < 2.75 and item >= 2.25 %}_25{% endif %}
                {% if item < 2.25 and item >= 1.75 %}_20{% endif %}
                {% if item < 1.75 and item >= 1.25 %}_15{% endif %}
                {% if item < 1.25 %}_10{% endif %}">
            <a href="{% url 'matrix:evaluations' gin.id tonic.id %}" style="text-decoration: none;">
                <div>{{ item|floatformat:1 }}</div>
            </a>
        </td>
        {% endif %}
        {% endfor %}
    </tr>
    {% endfor %}
</table>

gintonicmatrix/matrix/templates/matrix/ranking.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'matrix/style.css' %}">

<!doctype html>

<h1>Die Gin-Tonic-Rangliste</h1>

<p><a href="{% url 'matrix:index' %}">&lt Zur Matrix</a></p>

<form action="{% url 'matrix:ranking' %}" method="post">
    {% csrf_token %}
    <label for="countinput">Min. Bewertungen:</label>
    <input type="number" id="countinput" name="min_rating_count" min="0" value="{{ min_rating_count }}" style="width: 3em">
    <input type="submit" value="Speichern">
</form>

<table cellspacing="0" cellpadding="0">
    <tr>
        <th>Kombination</th>
        <th>⌀</th>
        <th>Anzahl Bewertungen</th>
        <th>Anzahl Trinker</th>
    </tr>
    {% for combination in combinations %}
    <tr>
        <td>{{ combination.name }}</td>
        <td class="
        {% if combination.rating >= 3.75 %}_40{% endif %}
        {% if combination.rating < 3.75 and combination.rating >= 3.25 %}_35{% endif %}
        {% if combination.rating < 3.25 and combination.rating >= 2.75 %}_30{% endif %}
        {% if combination.rating < 2.75 and combination.rating >= 2.25 %}_25{% endif %}
        {% if combination.rating < 2.25 and combination.rating >= 1.75 %}_20{% endif %}
        {% if combination.rating < 1.75 and combination.rating >= 1.25 %}_15{% endif %}
        {% if combination.rating < 1.25 %}_10{% endif %}">
            {{ combination.rating|floatformat:2 }}
        </td>
        <td>{{ combination.rating_count }}</td>
        <td>{{ combination.unique_rating_count }}</td>
    </tr>
    {% endfor %}
</table>